package me.ex;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "BB_DB".
 */
public class BB_db {

    private Long id;
    /** Not-null value. */
    private String NAME;
    private boolean SEX;
    private int eyer;

    public BB_db() {
    }

    public BB_db(Long id) {
        this.id = id;
    }

    public BB_db(Long id, String NAME, boolean SEX, int eyer) {
        this.id = id;
        this.NAME = NAME;
        this.SEX = SEX;
        this.eyer = eyer;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getNAME() {
        return NAME;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setNAME(String NAME) {
        this.NAME = NAME;
    }

    public boolean getSEX() {
        return SEX;
    }

    public void setSEX(boolean SEX) {
        this.SEX = SEX;
    }

    public int getEyer() {
        return eyer;
    }

    public void setEyer(int eyer) {
        this.eyer = eyer;
    }

}
