package me.ex;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import me.ex.AA_db;
import me.ex.BB_db;

import me.ex.AA_dbDao;
import me.ex.BB_dbDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig aA_dbDaoConfig;
    private final DaoConfig bB_dbDaoConfig;

    private final AA_dbDao aA_dbDao;
    private final BB_dbDao bB_dbDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        aA_dbDaoConfig = daoConfigMap.get(AA_dbDao.class).clone();
        aA_dbDaoConfig.initIdentityScope(type);

        bB_dbDaoConfig = daoConfigMap.get(BB_dbDao.class).clone();
        bB_dbDaoConfig.initIdentityScope(type);

        aA_dbDao = new AA_dbDao(aA_dbDaoConfig, this);
        bB_dbDao = new BB_dbDao(bB_dbDaoConfig, this);

        registerDao(AA_db.class, aA_dbDao);
        registerDao(BB_db.class, bB_dbDao);
    }
    
    public void clear() {
        aA_dbDaoConfig.getIdentityScope().clear();
        bB_dbDaoConfig.getIdentityScope().clear();
    }

    public AA_dbDao getAA_dbDao() {
        return aA_dbDao;
    }

    public BB_dbDao getBB_dbDao() {
        return bB_dbDao;
    }

}
