package com.json.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "CHANNEL_ITEM".
 */
public class ChannelItem implements java.io.Serializable {

    private Integer id;
    /** Not-null value. */
    private String name;
    private Integer orderId;
    private Integer selected;
    private String channelId;

    public ChannelItem() {
    }

    public ChannelItem(Integer id, String name, Integer orderId, Integer selected, String channelId) {
        this.id = id;
        this.name = name;
        this.orderId = orderId;
        this.selected = selected;
        this.channelId = channelId;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getName() {
        return name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(String name) {
        this.name = name;
    }

    public Integer getOrderId() {
        return orderId;
    }

    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    public Integer getSelected() {
        return selected;
    }

    public void setSelected(Integer selected) {
        this.selected = selected;
    }

    public String getChannelId() {
        return channelId;
    }

    public void setChannelId(String channelId) {
        this.channelId = channelId;
    }

}
